@baseUrl = http://localhost:3000

    ### Registrar usuário
# @name registerUser
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Admin Coordenador3",
    "matricula": "Admin12367",
    "senha": "123456",
    "perfil_id": 5
}

### Login 
# @name loginUser
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "perfil_id": 2,
    "matricula": "admin123",
    "senha": "123456"
}

### Listar perfis
GET {{baseUrl}}/users/perfis
Content-Type: application/json

### Criar perfil (Exige que tenha permissão de coordenador)
POST {{baseUrl}}/users/perfis
Content-Type: application/json

{
    "nome": "New Profile",
    "matricula": "NewProfile123",
    "senha": "password123"
}

### Deletar perfil
DELETE {{baseUrl}}/users/perfis/3
Content-Type: application/json
